spring:
  datasource:
    url: jdbc:mysql://47.95.226.40:3306/aoyo?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  application:
    name: spring security
  thymeleaf:
    mode: HMTL5
    encoding: UTF-8
    #热部署
    cache: false
#mybatis的配置
mybatis:
  #1.读取mapping映射文件
  mapper-locations: classpath:mapper/*.xml
  #2.驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    #3.懒加载
    #lazy-loading-enabled: true
    #4.起别名
  type-aliases-package: com.example.demo.pojo

  #打印日志
logging:
  level:
    com.example.demo.mapper: debug

#设置文件上传大小限制
#spring:
#  http:
#    multipart:
#      maxFileSize : 10Mb
#      maxRequestSize: 100Mb
#server:
#  connection-timeout: 18000000
#阿里云oss服务器
aliyun:
  access-id: LTAI4FgoqPc6enDjoEEk656A
  access-key: 9Wms1jqjl2k7UEupXJuWRJdp9uL6g5
  #创建bucket的名称
  bucket: oss-xys
  #服务器地址
  endpoint: oss-cn-beijing.aliyuncs.com
  #文件路径
  dir: lunbo
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql