spring:
  datasource:
    url: jdbc:mysql://47.95.226.40:3306/aoyo?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  application:
    name: spring security
  thymeleaf:
    mode: HMTL5
    encoding: UTF-8
    #热部署
    cache: false
#mybatis的配置
mybatis:
  #1.读取mapping映射文件
  mapper-locations: classpath:mapper/*.xml
  #2.驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    #3.懒加载
    #lazy-loading-enabled: true
    #4.起别名
  type-aliases-package: com.example.demo.pojo

  #打印日志
logging:
  level:
    com.example.demo.mapper: debug

